# Generated by Django 4.2.4 on 2024-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
