# Generated by Django 4.2.4 on 2024-12-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_company_name_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
