# Generated by Django 4.2.4 on 2024-12-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('project_experience', models.CharField(max_length=255)),
                ('other_details', models.TextField()),
                ('job_description', models.TextField()),
                ('evaluation_criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('resume_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('questions', models.TextField(null=True)),
                ('transcript', models.TextField(null=True)),
                ('interview_feedback', models.TextField(null=True)),
                ('matching_percentage', models.CharField(max_length=5, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='recruit.job')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_profiles', to='recruit.profile')),
            ],
        ),
    ]
