# Generated by Django 4.2.4 on 2025-01-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_alter_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Default Location', max_length=255),
        ),
    ]
