# Generated by Django 4.2.4 on 2025-01-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_job_created_at_job_job_status_job_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Glint AI', max_length=255),
        ),
    ]
