# Generated by Django 4.2.4 on 2025-01-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_alter_job_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_name',
            new_name='job_company_name',
        ),
    ]
