# Generated by Django 4.2.4 on 2025-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_rename_company_name_job_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='interview_link',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='interview_time',
            field=models.DateTimeField(null=True),
        ),
    ]
