# Generated by Django 4.2.4 on 2025-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_recruitment_interview_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='interview_time',
            field=models.CharField(null=True),
        ),
    ]
