# Generated by Django 4.2.4 on 2025-01-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0010_alter_recruitment_interview_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='interview_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='interview_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='interview_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='matching_percentage',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
