# Generated by Django 4.2.4 on 2025-01-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0011_alter_recruitment_interview_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='linkedin_response',
            field=models.CharField(null=True),
        ),
    ]
